export const MOVIE_LIST_REQUEST = 'MOVIE_LIST_REQUEST'
export const MOVIE_LIST_SUCCESS = 'MOVIE_LIST_SUCCESS'
export const MOVIE_LIST_FAILURE = 'MOVIE_LIST_FAILURE'

export const MOVIE_POST_REQUEST = 'MOVIE_POST_REQUEST'
export const MOVIE_POST_SUCCESS = 'MOVIE_POST_SUCCESS'
export const MOVIE_POST_FAILURE = 'MOVIE_POST_FAILURE'

export const MV_POST_REQUEST = 'MV_POST_REQUEST'
export const MV_POST_SUCCESS = 'MV_POST_SUCCESS'
export const MV_POST_FAILURE = 'MV_POST_FAILURE'

export const MV_LIST_REQUEST = 'MV_LIST_REQUEST'
export const MV_LIST_SUCCESS = 'MV_LIST_SUCCESS'
export const MV_LIST_FAILURE = 'MV_LIST_FAILURE'
