export const VIDEO_LIST_REQUEST = 'VIDEO_LIST_REQUEST'
export const VIDEO_LIST_SUCCESS = 'VIDEO_LIST_SUCCESS'
export const VIDEO_LIST_FAILURE = 'VIDEO_LIST_FAILURE'

export const VIDEO_ONE_REQUEST = 'VIDEO_ONE_REQUEST'
export const VIDEO_ONE_SUCCESS = 'VIDEO_ONE_SUCCESS'
export const VIDEO_ONE_FAILURE = 'VIDEO_ONE_FAILURE'
